## NumPy (Numerical Python)

    NumPy stands for Numerical Python. 
    It is a fundamental/ core library needed for scientific computing with Python, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Remember to Install Numpy 
pip install numpy


    In the first cell we put the code to import the numpy library as np. 
    This is for convenience; every time we need to use some functionality from the numpy library, we will write np instead of numpy.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

### The Basics

In [7]:
a = np.array([1,2,3,4,5], dtype='int32')
print(a)

[1 2 3 4 5]


In [6]:
# To check the size of an array
# For dtype=int32 = 104 + n * 4 Bytes => a = [1,2,3] => 96 + 3 * 4 = 116 
# For dtype=int64 = 96 + n * 8 Bytes => a = [1,2,3] => 96 + 3 * 8 = 120
# Whereas, 96 Bytes are allocated for other information of the array object (shape, dimension etc.).

import sys
sys.getsizeof(a)

114

In [21]:
np.linspace(0, 100, num=50)


array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [11]:
b = np.array([[9.0,8.0,7.0],
              [6.0,5.0,4],
              [6.0,5.0,4]])
print(b)
b.shape

[[9. 8. 7.]
 [6. 5. 4.]
 [6. 5. 4.]]


(3, 3)

In [44]:
# Get Dimension
b.ndim

2

In [45]:
# Get Shape
b.shape

(3, 3)

In [84]:
a = np.array(
            [       [ 
                       [ [1,1,1],
                         [2,2,2],
                         [3,3,3]],
                     
                       [ [3,3,9],
                         [4,4,9],
                         [3,3,9] ]  ],
                    [ 
                       [ [1,1,1],
                         [2,2,2],
                         [3,3,3]],
                     
                       [ [3,3,9],
                         [4,4,9],
                         [3,3,9] ]  ],
    
                    [  [ [5,5,9],
                         [6,6,9],
                         [3,3,9] ],
                       
                       [ [7,7,9],
                         [8,8,9],
                         [3,3,9] ]  ]
            ]
    
)


In [85]:
print("Dimensions: ", a.ndim)
print("Shape     : ", a.shape)

Dimensions:  4
Shape     :  (3, 2, 3, 3)


In [86]:
# Get Type
a.dtype

dtype('int32')

In [87]:
# Get Size (Size of one value i.e. size of one value of dtype='int64' = 8)
a.itemsize

4

In [88]:
# Get total size
a.nbytes

216

In [89]:
# Get number of elements
a.size

54

### Accessing/ Changing specific elements

In [90]:
a = np.array([[1, 2, 3,  4,  5,  6,  7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [97]:
# Get a specific element
a[0][0]
print(a[0,6])

7


In [104]:
# Get a specific row/ First value of first dimension and all values of second dimension
a[1, :2]

array([8, 9])

In [106]:
# Get a specific column/ All values of first dimension and third value of second dimension
a[:, 0:2]

array([[1, 2],
       [8, 9]])

In [115]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 0::2]

array([1, 3, 5, 7])

In [116]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [118]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-dim example

In [119]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [127]:
# Get specific element
b[0,1,1]
b[1, :]

array([[5, 6],
       [8, 8]])

In [128]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]

In [129]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [130]:
# All 0s matrix
z_mat = np.zeros((2,3))
z_mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [131]:
# All 1's Tensor
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [132]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [133]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [135]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [143]:
# Random decimal number
np.random.rand(5)*100

array([71.71334629, 46.80205191, 11.80756769, 44.84309327, 12.18272653])

In [144]:
# Random decimal numbers array
np.random.rand(4,2)

array([[0.07652774, 0.0083733 ],
       [0.99546189, 0.18099428],
       [0.02410209, 0.17284975],
       [0.4155316 , 0.16640201]])

In [147]:
# Random Integer values
np.random.randint(0,100, size=(4,3))

array([[42, 25, 17],
       [73, 80, 82],
       [98, 76, 55],
       [40, 90, 52]])

In [149]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [157]:
# Repeat an array
arr = np.array([[1,2,3]])
print(arr.shape)
r1 = np.repeat(arr,3, axis=0)
print(r1)

## In numpy axis = 1 by default. 
## axis = 0 along the rows,
## axis = 1 along the columns. 

(1, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [159]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [164]:
a = np.array([1,2,3])
b = a
print(a)
print(b)
b[0] = 100
print(a)

[1 2 3]
[1 2 3]
[100   2   3]


In [168]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics Functions

### Element-wise operations

In [170]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [171]:
a + 2

array([3, 4, 5, 6])

In [172]:
a - 2

array([-1,  0,  1,  2])

In [173]:
a * 2

array([2, 4, 6, 8])

In [174]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [175]:
a * a # Element wise multiplication

array([ 1,  4,  9, 16])

In [176]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [177]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [178]:
# Take the sin
degrees = 360
radians = (degrees * np.pi)/180
print(radians)
np.cos(radians) # Basically the method is used for radian, that's why we need to convert degree to radians first.


6.283185307179586


1.0

In [179]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [180]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [184]:
# Find the determinant
c = np.identity(3)
print(c)
det_v = np.linalg.det(c)
print(det_v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [187]:
# Find Trace (Return the sum along diagonals of the array.)
trace_val = np.trace(a)
print(trace_val)


2.0


In [188]:
e_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
e_mat.shape

(3, 3)

In [189]:
# Eigenvalues 
np.linalg.eigvals(e_mat)

array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16])

In [190]:
ab = np.array([[1,1,3],[1,2,1],[1,1,2]])

# Inverse
np.linalg.inv(ab)

array([[-3., -1.,  5.],
       [ 1.,  1., -2.],
       [ 1., -0., -1.]])

##### Statistics

In [195]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
np.min(stats)

1

In [202]:
np.max(stats, axis=1)

array([3, 6])

In [203]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [209]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("Shape: ", before.shape)

print("_______________\n")

after = before.reshape(1,8)
print(after)
print("Shape: ", after.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
_______________

[[1 2 3 4 5 6 7 8]]
Shape:  (1, 8)


In [210]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [211]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [212]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [215]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [216]:
filedata[~((filedata > 50) & (filedata < 100))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1])

In [217]:
# Python way to make copy from list/dictionaly/tuple etc
# mlist = [x for x in filedata]
# mlist